version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mognodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  
  backend:
    build: .
    container_name: subscription_backend
    depends_on:
      - mognodb
    ports:
      - "3000:8000"
    environment:
      - MONGO_URL: "mongodb://mongodb:27017/"

  volumes:
    mongodb_data: 